swiftrestapi:
    build: .
    command: bash -c "python init.py && gunicorn --debug --log-level debug -b 0.0.0.0:8888 restapi:app"
    ports:
      - "8888:8888"
    volumes:
      - /home/pc/restapi:/restapi
